name: ci

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses:  actions/checkout@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-build-action@v3
      -
        name: Build and test
        uses: docker/build-push-actions@v5
        with:
          context: .
          target: test
          load: true
      -
        name: Build and push 
        uses: docker/build-push-action@V5
        with:
          context: .
          push: true
          target: production
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
